### ISSUE TITLE
Proposal: a parameter to trigger just a syntax check and exit

### ISSUE THREAD

**Issue by matthiasries** [OpenVPN/openvpn#566]
Hi,
is there interest for a --check-syntax parameter. Using this parameter would check the syntax of the config file and the remaining parameters, then  exit with rc 0 or rc 1 in case of a syntax error.

I'm not sure if it should be call syntax-check, sanity-check or something else.

I almost get this behaviour if I add --version as the last parameter and check stdout for the string "OpenVPN".
The return code of openvpn is of course not 0
> openvpn --config test.ovpn --version |grep -q OpenVPN

This would for allow for a check in automation/deployment.
Ansible for example has the option to validate changes before applying them.

```
- name: add comp-lzo to openvpn config
  lineinfile:
    path: '/etc/openvpn/server.conf'
    regexp: '^comp-lzo'
    insertafter: '^client'
    line: 'comp-lzo'
    validate: "openvpn --check-syntax --config '%s' "
  notify: restart-openvpn
```
